-- Run this in the new Supabase project SQL Editor AFTER running schema.sql
-- Disables RLS on all tables so the app works with the anon/service keys

ALTER TABLE apparatus DISABLE ROW LEVEL SECURITY;
ALTER TABLE skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE levels DISABLE ROW LEVEL SECURITY;
ALTER TABLE level_apparatus DISABLE ROW LEVEL SECURITY;
ALTER TABLE level_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE fee_structures DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE coach_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE coach_levels DISABLE ROW LEVEL SECURITY;
ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE student_batches DISABLE ROW LEVEL SECURITY;
ALTER TABLE competitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE competition_age_groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE competition_age_group_apparatus DISABLE ROW LEVEL SECURITY;
ALTER TABLE competition_apparatus_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE competition_shortlist DISABLE ROW LEVEL SECURITY;
ALTER TABLE competition_enrollments DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum DISABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_skills DISABLE ROW LEVEL SECURITY;
ALTER TABLE feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE fee_collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcement_reads DISABLE ROW LEVEL SECURITY;
